<?php
/**
 * Editorial Review Queue for AI-Generated Posts
 *
 * Adds review status, quality score, and approval workflow
 * for posts generated by the AI system.
 */

// Register review meta fields
function intentflow_register_review_meta() {
    $fields = array(
        '_intentflow_review_status'  => 'string',   // pending_review, approved, needs_edit, rejected
        '_intentflow_quality_score'  => 'integer',   // 0-100
        '_intentflow_review_notes'   => 'string',
        '_intentflow_fact_checked'   => 'boolean',
        '_intentflow_plagiarism_ok'  => 'boolean',
    );

    foreach ($fields as $key => $type) {
        register_post_meta('post', $key, array(
            'show_in_rest'  => true,
            'single'        => true,
            'type'          => $type,
            'auth_callback' => function () { return current_user_can('edit_posts'); },
        ));
    }
}
add_action('init', 'intentflow_register_review_meta');

// Add review meta box
function intentflow_review_meta_box() {
    add_meta_box(
        'intentflow_review',
        __('Editorial Review', 'intentflow'),
        'intentflow_review_meta_box_html',
        'post',
        'side',
        'high'
    );
}
add_action('add_meta_boxes', 'intentflow_review_meta_box');

function intentflow_review_meta_box_html($post) {
    $ai_generated = get_post_meta($post->ID, '_intentflow_ai_generated', true);
    $status       = get_post_meta($post->ID, '_intentflow_review_status', true) ?: ($ai_generated ? 'pending_review' : '');
    $score        = (int) get_post_meta($post->ID, '_intentflow_quality_score', true);
    $notes        = get_post_meta($post->ID, '_intentflow_review_notes', true);
    $fact_checked = get_post_meta($post->ID, '_intentflow_fact_checked', true);
    $plag_ok      = get_post_meta($post->ID, '_intentflow_plagiarism_ok', true);

    wp_nonce_field('intentflow_review_nonce', '_intentflow_review_nonce');

    if (!$ai_generated && empty($status)) {
        echo '<p style="color:#666;font-size:12px">' . esc_html__('Not AI-generated. Review queue is for AI posts.', 'intentflow') . '</p>';
        return;
    }

    $status_colors = array(
        'pending_review' => '#F59E0B',
        'needs_edit'     => '#EF4444',
        'approved'       => '#22C55E',
        'rejected'       => '#6B7280',
    );
    $status_labels = array(
        'pending_review' => __('Pending Review', 'intentflow'),
        'needs_edit'     => __('Needs Human Edit', 'intentflow'),
        'approved'       => __('Approved', 'intentflow'),
        'rejected'       => __('Rejected', 'intentflow'),
    );
    ?>
    <div>
        <!-- Status -->
        <div style="margin-bottom:10px">
            <label style="font-weight:600;font-size:12px;display:block;margin-bottom:3px"><?php esc_html_e('Review Status', 'intentflow'); ?></label>
            <select name="_intentflow_review_status" style="width:100%">
                <?php foreach ($status_labels as $val => $label) : ?>
                    <option value="<?php echo esc_attr($val); ?>" <?php selected($status, $val); ?>><?php echo esc_html($label); ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <!-- Quality Score -->
        <div style="margin-bottom:10px">
            <label style="font-weight:600;font-size:12px;display:block;margin-bottom:3px"><?php esc_html_e('Quality Score', 'intentflow'); ?> (0-100)</label>
            <input type="number" name="_intentflow_quality_score" value="<?php echo esc_attr($score); ?>" min="0" max="100" style="width:100%">
            <?php if ($score > 0) : ?>
                <div style="margin-top:4px;height:6px;background:#e5e7eb;border-radius:4px;overflow:hidden">
                    <div style="height:100%;width:<?php echo $score; ?>%;background:<?php echo $score >= 70 ? '#22C55E' : ($score >= 40 ? '#F59E0B' : '#EF4444'); ?>;border-radius:4px"></div>
                </div>
            <?php endif; ?>
        </div>

        <!-- Checklist -->
        <div style="margin-bottom:10px">
            <label style="font-weight:600;font-size:12px;display:block;margin-bottom:6px"><?php esc_html_e('Checklist', 'intentflow'); ?></label>
            <label style="display:flex;align-items:center;gap:6px;font-size:12px;margin-bottom:4px">
                <input type="checkbox" name="_intentflow_fact_checked" value="1" <?php checked($fact_checked); ?>>
                <?php esc_html_e('Fact-checked', 'intentflow'); ?>
            </label>
            <label style="display:flex;align-items:center;gap:6px;font-size:12px">
                <input type="checkbox" name="_intentflow_plagiarism_ok" value="1" <?php checked($plag_ok); ?>>
                <?php esc_html_e('No plagiarism concerns', 'intentflow'); ?>
            </label>
        </div>

        <!-- Notes -->
        <div>
            <label style="font-weight:600;font-size:12px;display:block;margin-bottom:3px"><?php esc_html_e('Review Notes', 'intentflow'); ?></label>
            <textarea name="_intentflow_review_notes" rows="3" style="width:100%;font-size:12px" placeholder="<?php esc_attr_e('Add notes about what needs editing...', 'intentflow'); ?>"><?php echo esc_textarea($notes); ?></textarea>
        </div>
    </div>
    <?php
}

// Save review meta
function intentflow_save_review_meta($post_id) {
    if (!isset($_POST['_intentflow_review_nonce']) || !wp_verify_nonce($_POST['_intentflow_review_nonce'], 'intentflow_review_nonce')) return;
    if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
    if (!current_user_can('edit_post', $post_id)) return;

    $text_fields = array('_intentflow_review_status', '_intentflow_review_notes');
    foreach ($text_fields as $key) {
        if (isset($_POST[$key])) {
            update_post_meta($post_id, $key, sanitize_text_field($_POST[$key]));
        }
    }

    if (isset($_POST['_intentflow_quality_score'])) {
        update_post_meta($post_id, '_intentflow_quality_score', min(100, max(0, absint($_POST['_intentflow_quality_score']))));
    }

    update_post_meta($post_id, '_intentflow_fact_checked', !empty($_POST['_intentflow_fact_checked']));
    update_post_meta($post_id, '_intentflow_plagiarism_ok', !empty($_POST['_intentflow_plagiarism_ok']));
}
add_action('save_post_post', 'intentflow_save_review_meta');

// Auto-set review status for AI-generated posts
function intentflow_auto_review_status($post_id) {
    $ai_gen = get_post_meta($post_id, '_intentflow_ai_generated', true);
    $status = get_post_meta($post_id, '_intentflow_review_status', true);

    if ($ai_gen && empty($status)) {
        update_post_meta($post_id, '_intentflow_review_status', 'pending_review');
    }
}
add_action('save_post_post', 'intentflow_auto_review_status', 20);

// Add review status column to posts list
function intentflow_review_admin_column($columns) {
    $new = array();
    foreach ($columns as $key => $label) {
        $new[$key] = $label;
        if ($key === 'title') {
            $new['review_status'] = __('Review', 'intentflow');
        }
    }
    return $new;
}
add_filter('manage_posts_columns', 'intentflow_review_admin_column');

function intentflow_review_admin_column_data($column, $post_id) {
    if ($column !== 'review_status') return;

    $status = get_post_meta($post_id, '_intentflow_review_status', true);
    if (empty($status)) { echo '—'; return; }

    $colors = array('pending_review' => '#F59E0B', 'needs_edit' => '#EF4444', 'approved' => '#22C55E', 'rejected' => '#6B7280');
    $labels = array('pending_review' => '⏳ Review', 'needs_edit' => '✏️ Edit', 'approved' => '✅ OK', 'rejected' => '❌ No');

    $color = $colors[$status] ?? '#6B7280';
    $label = $labels[$status] ?? $status;

    printf('<span style="color:%s;font-weight:600;font-size:12px">%s</span>', esc_attr($color), esc_html($label));

    $score = (int) get_post_meta($post_id, '_intentflow_quality_score', true);
    if ($score > 0) {
        printf('<br><span style="font-size:11px;color:#666">Score: %d</span>', $score);
    }
}
add_action('manage_posts_custom_column', 'intentflow_review_admin_column_data', 10, 2);
